[project]
name = "mcp-demo-remote"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.118.0",
    "fastmcp>=2.12.4",
    "pydantic>=2.11.9",
]
